name: Build Strapi Admin

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Strapi admin
        run: yarn build

      - name: Commit build output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/build
          git commit -m "ci: build admin" || echo "No changes"
          git push
